[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "flus-ca"
version = "0.3.0"
description = "Python implementation of the FLUS cellular automata land-use allocation model"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "rasterio",
    "numba",
    "pandas",
    "pyyaml"
]

[project.optional-dependencies]
test = ["pytest"]

[project.scripts]
flus-ca = "flus_ca.cli:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["flus_ca*"]
